---
- name: Configure Fedora Silverblue system
  hosts: fedora
  remote_user: leo

  tasks:
  - name: Add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user
  - name: Install flatpaks
    community.general.flatpak:
      name:
        - com.dropbox.Client
        - md.obsidian.Obsidian
        - org.signal.Signal
      method: user
      state: present
